### ISSUE TITLE
Menu items characters encoding issue

### ISSUE THREAD

**Issue by BrElio** [jchristopher/searchwp-modal-search-form#15]
If any menu item has a name that includes accents the accented character encoding is lost when SearchWP Modal is active.

The issue is located in `Menu.php` in the `wp_nave_menu` function.

when `$dom->loadHTML( $nav_menu );` is called the encoding is lost.

A possible solution that seems to work could be to change that line with:

`$dom->loadHTML( utf8_decode( $nav_menu ) );`

**Comment by hofmannsven** [comment]
Can confirm. I have the same issue with German umlauts. The suggested solution fixes this encoding.
